version: '3'

services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: proxy_container
    ports:
      - "2000:2000/udp"
  json-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: json_server
    ports:
      - "2001:2001/udp"
    command: ["go", "run", "server/main.go", "2001", "json"]
  xml-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: xml_server
    ports:
      - "2002:2002/udp"
    command: ["go", "run", "server/main.go", "2002", "xml"]
  yaml-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yaml_server
    ports:
      - "2003:2003/udp"
    command: ["go", "run", "server/main.go", "2003", "yaml"]
